surrogates:
  - name: openclip_vit_b32
    backend: open_clip
    model_name: ViT-B-32
    pretrained: laion2b_s34b_b79k

  - name: openclip_vit_b16
    backend: open_clip
    model_name: ViT-B-16
    pretrained: laion2b_s34b_b88k

  - name: openclip_vit_l14
    backend: open_clip
    model_name: ViT-L-14
    pretrained: laion2b_s32b_b82k
